# Generated by Django 5.0.1 on 2024-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='other_person_name_reply',
            new_name='other_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_name_reply',
            new_name='other_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='self_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='self_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
