# Generated by Django 5.0.1 on 2024-07-25 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_rename_other_person_name_reply_question_other_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4)),
                ('temporary_question', models.CharField(max_length=255)),
            ],
        ),
    ]
