# Generated by Django 5.0.1 on 2024-07-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_temporaryquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryquestion',
            old_name='temporary_question',
            new_name='question',
        ),
    ]
