# Generated by Django 5.0.1 on 2024-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_rename_temporary_question_temporaryquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=8, unique=True)),
                ('long_url', models.URLField()),
            ],
        ),
    ]
