# Generated by Django 5.0.1 on 2024-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='receiver_email',
            field=models.EmailField(default='1234@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='room',
            name='sender_email',
            field=models.EmailField(default='1234@gmail.com', max_length=254),
        ),
    ]
