# Generated by Django 5.0.1 on 2024-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_room_receiver_email_room_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_modification',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
