# Generated by Django 5.0.1 on 2024-08-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_room_last_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_modification',
            field=models.DateField(auto_now=True),
        ),
    ]
