# Generated by Django 5.0.1 on 2024-08-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_room_last_modification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryQuestion',
        ),
    ]
