# Generated by Django 5.0.1 on 2024-08-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_delete_temporaryquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shortURL',
        ),
    ]
